image: docker:latest

stages:
    - build
    - test
    - deploy

variables:
    GIT_DEPTH: "50"
    DOCKER_IMAGE: $CI_PROJECT_NAME:$CI_COMMIT_REF_NAME

build:
    stage: build
    before_script:
        - docker info
    script:
        - docker build -t $DOCKER_IMAGE .

test:
    stage: test
    script:
        - . run-tests
    except:
        - master

deploy:
    stage: deploy
    image: bryanyang0528/aws_docker:latest
    variables:
        ECS_IMAGE: ${ECR_PATH}/$DOCKER_IMAGE
    script:
        - $(aws ecr get-login --no-include-email --region ap-northeast-1)
        - docker tag $DOCKER_IMAGE $ECS_IMAGE
        - docker push $ECS_IMAGE
    when: manual
    only:
        - master