#!/bin/bash
set -x

pip install --upgrade pip setuptools
pip install coverage mock nose pyspark==2.2.1

nosetests \
    --logging-level=INFO \
    --detailed-errors \
    --verbosity=2 \
    --with-coverage \
    --cover-package .\
    --cover-erase
